var langConstant = "en";
var lang = {
    MemoryToolBarTitle: "MEMORY",
    MemoryInnerToolBarTitle: "memory:",
    OutputToolBarTitle: "OUTPUT",
    BegginingBlockBegin: "Begin",
    BegginingBlockEnd: "End",
    WhileBlockCondition: "While",
    DoWhileBlockCondition: "While",
    IfBlockTrueCondition: "True",
    IfBlockFalseCondition: "False",
    CodeTitleSentence: "Pseudocode",
    //New Block PopUp
    NewBlockitlePopUp: "Choose Block to Create",
    //Container Block PopUp
    ContainerBlockTitlePopUp: "Create New Block",
    ContainerBlockMessagePopUp: "Insert a valid expression: ",
    ContainerBlockEditMessagePopUp: "Edit block expression: ",
    ContainerBlockEditTitlePopUp: "Edit Block",
    //Define Block PopUp
    DefineBlockTitlePopUp: "Create New Block",
    DefineBlockEditTitlePopUp: "Edit Block",
    DefineErrorErasingBlockMessage: "By erasing this varibale you might cause some colateral, check for highlited blocks",
    DefineBlockVariableTypeLabel: "Variable Type:",
    DefineBlockVariableNameLabel: "Variable Name:",
    DefineBlockVariableValueLabel: "Default Value:",
    //variableTypesName
    variableTypesNameNumber: "number",
    variableTypesNameString: "string",
    variableTypesNameBoolean: "boolean",
    //Read Block PopUp
    ReadBlockInstructionPopUp: "Variable to read :",
    ReadBlockTitlePopUp: "Create New Block",
    ReadBlockPopUpError: "No variables to be selected!",
    ReadBlockExecutionTextOne: "Insert value for ",
    ReadBlockExecutionTextTwo: "and press confirm :",
    ReadBlockEditTitlePopUp: "Edit Block",
    BreakBlockEditTitlePopUp: "Edit Block",
    //Button Translations 
    ButtonCreatePopUp: "Create Block",
    CloseButtonSentence: "Close",
    ButtonEditPopUp: "Edit Block",
    ButtonRemovePopUp: "Remove Block",
    ButtonCancelPopUp: "Cancel",
    ButtonConfirmPopUp: "Confirm",
    //Block name translation
    WhileBlock: "While Block",
    IfBlock: "If Block",
    DefineBlock: "Define Block",
    ReadBlock: "Read Block",
    ExecuteBlock: "Execute Block",
    WriteBlock: "Write Block",
    DoWhileBlock: "Do While Block",
    BreakBlock: "Break block",
    ContinueBlock: "Break block",
    //BreakBlock Fixed Instruction
    BreakBlockInstruction: "Break",
    ContinueBlockInstruction: "Contiue",
    //HelpPopUp
    HelpPopUpAbout: "About",
    HelpPopUpTitle: "Help Menu",
    HelpPopUpTemplateTab: "Algorithms",
    HelpPopUpBlocksTab: "Blocks",
};
var fluxogramLanguageEN = {
    MemoryToolBarTitle: "MEMORY",
    MemoryInnerToolBarTitle: "memory:",
    OutputToolBarTitle: "OUTPUT",
    BegginingBlockBegin: "Begin",
    BegginingBlockEnd: "End",
    WhileBlockCondition: "While",
    DoWhileBlockCondition: "While",
    IfBlockTrueCondition: "True",
    IfBlockFalseCondition: "False",
    CodeTitleSentence: "Pseudocode",
    //New Block PopUp
    NewBlockitlePopUp: "Choose Block to Create",
    //Container Block PopUp
    ContainerBlockTitlePopUp: "Create New Block",
    ContainerBlockMessagePopUp: "Insert a valid expression: ",
    ContainerBlockEditMessagePopUp: "Edit block expression: ",
    ContainerBlockEditTitlePopUp: "Edit Block",
    //Define Block PopUp
    DefineBlockTitlePopUp: "Create New Block",
    DefineBlockEditTitlePopUp: "Edit Block",
    DefineErrorErasingBlockMessage: "By erasing this varibale you might cause some colateral, check for highlited blocks",
    DefineBlockVariableTypeLabel: "Variable Type:",
    DefineBlockVariableNameLabel: "Variable Name:",
    DefineBlockVariableValueLabel: "Default Value:",
    //variableTypesName
    variableTypesNameNumber: "number",
    variableTypesNameString: "string",
    variableTypesNameBoolean: "boolean",
    //Read Block PopUp
    ReadBlockInstructionPopUp: "Variable to read :",
    ReadBlockTitlePopUp: "Create New Block",
    ReadBlockPopUpError: "No variables to be selected!",
    ReadBlockExecutionTextOne: "Insert value for ",
    ReadBlockExecutionTextTwo: "and press confirm :",
    ReadBlockEditTitlePopUp: "Edit Block",
    BreakBlockEditTitlePopUp: "Edit Block",
    //Button Translations 
    ButtonCreatePopUp: "Create Block",
    CloseButtonSentence: "Close",
    ButtonEditPopUp: "Edit Block",
    ButtonRemovePopUp: "Remove Block",
    ButtonCancelPopUp: "Cancel",
    ButtonConfirmPopUp: "Confirm",
    //Block name translation
    WhileBlock: "While Block",
    IfBlock: "If Block",
    DefineBlock: "Define Block",
    ReadBlock: "Read Block",
    ExecuteBlock: "Execute Block",
    WriteBlock: "Write Block",
    DoWhileBlock: "Do While Block",
    BreakBlock: "Break block",
    ContinueBlock: "Break block",
    //BreakBlock Fixed Instruction
    BreakBlockInstruction: "Break",
    ContinueBlockInstruction: "Contiue",
    //HelpPopUp
    HelpPopUpAbout: "About",
    HelpPopUpTitle: "Help Menu",
    HelpPopUpTemplateTab: "Algorithms",
    HelpPopUpBlocksTab: "Blocks",
};
//# sourceMappingURL=resourceEN.js.map