var langConstant = "en";
var lang = {
    MemoryToolBarTitle: "MEMORY",
    OutputToolBarTitle: "OUTPUT",
    BegginingBlockBegin: "Begin",
    BegginingBlockEnd: "End",
    WhileBlockCondition: "While",
    DoWhileBlockCondition: "While",
    IfBlockTrueCondition: "True",
    IfBlockFalseCondition: "False",
    CodeTitleSentence: "Pseudocode",
    //New Block PopUp
    NewBlockitlePopUp: "Choose Block to Create",
    //Container Block PopUp
    ContainerBlockTitlePopUp: "Create New Block",
    ContainerBlockMessagePopUp: "Insert a valid expression: ",
    ContainerBlockEditMessagePopUp: "Edit block expression: ",
    ContainerBlockEditTitlePopUp: "Edit Block",
    //Define Block PopUp
    DefineBlockTitlePopUp: "Create New Block",
    DefineBlockEditTitlePopUp: "Edit Block",
    DefineErrorErasingBlockMessage: "By erasing this varibale you might cause some colateral, check for highlited blocks",
    DefineBlockVariableTypeLabel: "Variable Type:",
    DefineBlockVariableNameLabel: "Variable Name:",
    DefineBlockVariableValueLabel: "Default Value:",
    //variableTypesName
    variableTypesNameNumber: "number",
    variableTypesNameString: "string",
    variableTypesNameBoolean: "boolean",
    //Read Block PopUp
    ReadBlockInstructionPopUp: "Variable to read :",
    ReadBlockTitlePopUp: "Create New Block",
    ReadBlockPopUpError: "No variables to be selected!",
    ReadBlockExecutionTextOne: "Insert value for ",
    ReadBlockExecutionTextTwo: "and press confirm :",
    ReadBlockEditTitlePopUp: "Edit Block",
    BreakBlockEditTitlePopUp: "Edit Block",
    //Button Translations 
    ButtonCreatePopUp: "Create Block",
    CloseButtonSentence: "Close",
    ButtonEditPopUp: "Edit Block",
    ButtonRemovePopUp: "Remove Block",
    ButtonCancelPopUp: "Cancel",
    ButtonConfirmPopUp: "Confirm",
    //Block name translation
    WhileBlock: "While Block",
    IfBlock: "If Block",
    DefineBlock: "Define Block",
    ReadBlock: "Read Block",
    ExecuteBlock: "Execute Block",
    WriteBlock: "Write Block",
    DoWhileBlock: "Do While Block",
    BreakBlock: "Break block",
    ContinueBlock: "Break block",
    //BreakBlock Fixed Instruction
    BreakBlockInstruction: "Break",
    ContinueBlockInstruction: "Contiue",
    //HelpPopUp
    HelpPopUpAbout: "About",
    HelpPopUpTitle: "Help Menu",
    HelpPopUpTemplateTab: "Algorithms",
    HelpPopUpBlocksTab: "Blocks",
};
var fluxogramLanguageEN = {
    MemoryToolBarTitle: "MEMORY",
    OutputToolBarTitle: "OUTPUT",
    BegginingBlockBegin: "Begin",
    BegginingBlockEnd: "End",
    WhileBlockCondition: "While",
    DoWhileBlockCondition: "While",
    IfBlockTrueCondition: "True",
    IfBlockFalseCondition: "False",
    CodeTitleSentence: "Pseudocode",
    //New Block PopUp
    NewBlockitlePopUp: "Choose Block to Create",
    //Container Block PopUp
    ContainerBlockTitlePopUp: "Create New Block",
    ContainerBlockMessagePopUp: "Insert a valid expression: ",
    ContainerBlockEditMessagePopUp: "Edit block expression: ",
    ContainerBlockEditTitlePopUp: "Edit Block",
    //Define Block PopUp
    DefineBlockTitlePopUp: "Create New Block",
    DefineBlockEditTitlePopUp: "Edit Block",
    DefineErrorErasingBlockMessage: "By erasing this varibale you might cause some colateral, check for highlited blocks",
    DefineBlockVariableTypeLabel: "Variable Type:",
    DefineBlockVariableNameLabel: "Variable Name:",
    DefineBlockVariableValueLabel: "Default Value:",
    //variableTypesName
    variableTypesNameNumber: "number",
    variableTypesNameString: "string",
    variableTypesNameBoolean: "boolean",
    //Read Block PopUp
    ReadBlockInstructionPopUp: "Variable to read :",
    ReadBlockTitlePopUp: "Create New Block",
    ReadBlockPopUpError: "No variables to be selected!",
    ReadBlockExecutionTextOne: "Insert value for ",
    ReadBlockExecutionTextTwo: "and press confirm :",
    ReadBlockEditTitlePopUp: "Edit Block",
    BreakBlockEditTitlePopUp: "Edit Block",
    //Button Translations 
    ButtonCreatePopUp: "Create Block",
    CloseButtonSentence: "Close",
    ButtonEditPopUp: "Edit Block",
    ButtonRemovePopUp: "Remove Block",
    ButtonCancelPopUp: "Cancel",
    ButtonConfirmPopUp: "Confirm",
    //Block name translation
    WhileBlock: "While Block",
    IfBlock: "If Block",
    DefineBlock: "Define Block",
    ReadBlock: "Read Block",
    ExecuteBlock: "Execute Block",
    WriteBlock: "Write Block",
    DoWhileBlock: "Do While Block",
    BreakBlock: "Break block",
    ContinueBlock: "Break block",
    //BreakBlock Fixed Instruction
    BreakBlockInstruction: "Break",
    ContinueBlockInstruction: "Contiue",
    //HelpPopUp
    HelpPopUpAbout: "About",
    HelpPopUpTitle: "Help Menu",
    HelpPopUpTemplateTab: "Algorithms",
    HelpPopUpBlocksTab: "Blocks",
};
var fluxogramLanguagePT = {
    MemoryToolBarTitle: "MEMÓRIA",
    OutputToolBarTitle: "CONSOLA",
    BegginingBlockBegin: "Início",
    BegginingBlockEnd: "Fim",
    WhileBlockCondition: "Enquanto",
    DoWhileBlockCondition: "Enquanto",
    IfBlockTrueCondition: "Verdadeiro",
    IfBlockFalseCondition: "Falso",
    CodeTitleSentence: "Pseudocódigo",
    //New Block PopUp
    NewBlockitlePopUp: "Escolha o tipo de bloco a criar",
    //Container Block PopUp
    ContainerBlockTitlePopUp: "Criar Novo Bloco",
    ContainerBlockMessagePopUp: "Insira uma expressão válida: ",
    ContainerBlockEditMessagePopUp: "Edite a expressão do bloco: ",
    ContainerBlockEditTitlePopUp: "Editar Bloco",
    //Define Block PopUp
    DefineBlockTitlePopUp: "Criar Novo Bloco",
    DefineBlockEditTitlePopUp: "Editar Bloco",
    DefineErrorErasingBlockMessage: "Apagando este bloco, o fluxograma poderá ficar inválido, tente editar os blocos a amarelo.",
    DefineBlockVariableTypeLabel: "Tipo da variável:",
    DefineBlockVariableNameLabel: "Nome da variável:",
    DefineBlockVariableValueLabel: "Valor por defeito:",
    //variableTypesName
    variableTypesNameNumber: "número",
    variableTypesNameString: "texto",
    variableTypesNameBoolean: "lógico",
    //Read Block PopUp
    ReadBlockInstructionPopUp: "Variável a ler :",
    ReadBlockTitlePopUp: "Criar Novo Bloco",
    ReadBlockPopUpError: "Não existem variáveis para ler!",
    ReadBlockExecutionTextOne: "Insira o valor de ",
    ReadBlockExecutionTextTwo: " e pressione confirmar :",
    ReadBlockEditTitlePopUp: "Editar Bloco",
    BreakBlockEditTitlePopUp: "Editar Bloco",
    //Button Translations 
    ButtonCreatePopUp: "Criar Bloco",
    CloseButtonSentence: "Fechar",
    ButtonEditPopUp: "Editar Bloco",
    ButtonRemovePopUp: "Remover Bloco",
    ButtonCancelPopUp: "Cancelar",
    ButtonConfirmPopUp: "Confirmar",
    //Block name translation
    WhileBlock: "Bloco Enquanto",
    IfBlock: "Bloco Se / Não",
    DefineBlock: "Bloco Declarar",
    ReadBlock: "Bloco Ler",
    ExecuteBlock: "Bloco Executar",
    WriteBlock: "Bloco Escrever",
    DoWhileBlock: "Bloco Faz Enquanto",
    BreakBlock: "Bloco Quebra",
    ContinueBlock: "Bloco Continuar",
    //BreakBlock Fixed Instruction
    BreakBlockInstruction: "Quebra",
    ContinueBlockInstruction: "Continuar",
    //HelpPopUp
    HelpPopUpAbout: "Sobre",
    HelpPopUpTitle: "Menu de Ajuda",
    HelpPopUpTemplateTab: "Algoritmos",
    HelpPopUpBlocksTab: "Blocos",
};
//# sourceMappingURL=resource.js.map